### ISSUE TITLE
v1.1 stuck on compiling plot.... after /save command

### ISSUE THREAD

**Issue by NFT2626** [CreativerseMC/CreativerseMC-Plugin#2]
[14:24:06 INFO]: G26267817 issued server command: /save
[14:24:07 INFO]: [STDOUT] Processing chunks...
[14:24:07 INFO]: [STDOUT] Reading Chunks:0.0012821
[14:24:07 INFO]: [STDOUT] Writing File:4.2E-5
[14:24:07 INFO]: [STDOUT] OBJ Export Time:0.0025438
[14:24:07 INFO]: [STDOUT] Saved model to C:\Users\uscha\Desktop\chadcraftv2 (1)\plugins\Creativerse\..\..\cache\1645709047386.obj
[14:24:07 INFO]: [STDOUT] Sorting OBJ file...
[14:24:07 INFO]: [STDOUT] Writing materials to C:\Users\uscha\Desktop\chadcraftv2 (1)\plugins\Creativerse\..\..\cache\1645709047386.mtl...
[14:24:07 INFO]: [STDOUT] Exporting textures...
[14:24:07 INFO]: [STDOUT] Export Time:0.0191935
[14:24:07 INFO]: [STDOUT] Done!
[14:24:07 WARN]: java.lang.IllegalArgumentException: count < 1
[14:24:07 WARN]: 	at Creativerse.jar//de.javagl.jgltf.impl.v2.Accessor.setCount(Accessor.java:246)
[14:24:07 WARN]: 	at Creativerse.jar//de.javagl.jgltf.model.impl.creation.BufferStructureGltfV2.createAccessor(BufferStructureGltfV2.java:89)
[14:24:07 WARN]: 	at Creativerse.jar//de.javagl.jgltf.model.impl.creation.BufferStructureGltfV2.createAccessors(BufferStructureGltfV2.java:67)
[14:24:07 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.creator.ObjGltfAssetCreatorV2.convert(ObjGltfAssetCreatorV2.java:277)
[14:24:07 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.creator.ObjGltfAssetCreatorV2.create(ObjGltfAssetCreatorV2.java:202)
[14:24:07 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.ConvertObjToGltf.convert(ConvertObjToGltf.java:103)
[14:24:07 WARN]: 	at Creativerse.jar//com.creativerse.renderer.McTo3D.convertObjToGltf(McTo3D.java:48)
[14:24:07 WARN]: 	at Creativerse.jar//com.creativerse.commands.Save.lambda$onCommand$0(Save.java:93)
[14:24:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:24:10 WARN]: java.io.FileNotFoundException: plugins\Creativerse\..\..\cache\1645709047386.gltf (Le fichier spécifié est introuvable)
[14:24:10 WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[14:24:10 WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[14:24:10 WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[14:24:10 WARN]: 	at Creativerse.jar//com.creativerse.requests.Request.upload(Request.java:20)
[14:24:10 WARN]: 	at Creativerse.jar//com.creativerse.Nft.createJSON(Nft.java:24)
[14:24:10 WARN]: 	at Creativerse.jar//com.creativerse.commands.Save.lambda$onCommand$0(Save.java:100)
[14:24:10 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CreativerseMC** [comment]
Fixed in Release v1.2.1 https://github.com/CreativerseMC/CreativerseMC-Plugin/releases/tag/v1.2.1
